---
- name: Running Backups
  hosts: cisco
  gather_facts: false

  tasks:
          - name: IOS
            ios_command:
                    commands:
                            - show run
            register: config
            when: ansible_network_os == "ios"
          - name: saving
            copy:
                     content: "{{ config.stdout[0 ]}}"
                     dest: "/home/admin/Ansible_lab01/backups/backup_ios_{{ inventory_hostname }}.txt"
            when: ansible_network_os == "ios"
...
